/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Felipe's Laptop
 */
public class Info extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public Info() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelObrigado = new javax.swing.JLabel();
        labelAlunos = new javax.swing.JLabel();
        labelFelipe = new javax.swing.JLabel();
        labelRafael = new javax.swing.JLabel();
        labelProf = new javax.swing.JLabel();
        labelFabricio = new javax.swing.JLabel();
        labelDisciplina = new javax.swing.JLabel();
        labelProgra = new javax.swing.JLabel();
        labelAno = new javax.swing.JLabel();
        labelUTFPR = new javax.swing.JLabel();
        labelUniversidade = new javax.swing.JLabel();
        labelCampus = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Informações"); // NOI18N

        labelObrigado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelObrigado.setText("Obrigado por utilizar!");

        labelAlunos.setText("Alunos: ");

        labelFelipe.setText("Felipe Seolin Bento");

        labelRafael.setText("Rafael Fernandes Marques");

        labelProf.setText("Professor:");

        labelFabricio.setText("Fabrício Martins Lopes");

        labelDisciplina.setText("Disciplina:");

        labelProgra.setText("Programação Desktop - SO35A");

        labelAno.setText("2018/2");

        labelUTFPR.setText("UTFPR");

        labelUniversidade.setText("Universidade Tecnológica Federal do Paraná");

        labelCampus.setText("Câmpus Cornélio Procópio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAlunos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelProf)
                            .addComponent(labelDisciplina))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(labelObrigado))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(labelFabricio))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(labelFelipe))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(labelRafael))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(labelCampus)
                                        .addComponent(labelUTFPR)
                                        .addComponent(labelUniversidade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelProgra)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelAno)))))
                        .addContainerGap(120, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(labelObrigado)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlunos)
                    .addComponent(labelFelipe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRafael)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProf)
                    .addComponent(labelFabricio))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDisciplina)
                    .addComponent(labelProgra)
                    .addComponent(labelAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(labelUTFPR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUniversidade)
                .addGap(8, 8, 8)
                .addComponent(labelCampus)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAlunos;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelCampus;
    private javax.swing.JLabel labelDisciplina;
    private javax.swing.JLabel labelFabricio;
    private javax.swing.JLabel labelFelipe;
    private javax.swing.JLabel labelObrigado;
    private javax.swing.JLabel labelProf;
    private javax.swing.JLabel labelProgra;
    private javax.swing.JLabel labelRafael;
    private javax.swing.JLabel labelUTFPR;
    private javax.swing.JLabel labelUniversidade;
    // End of variables declaration//GEN-END:variables
}
